# 2.1.1. Getting Started

### In PyTorch, there are **two main types of functions**:

### 1. Module (Factory) Functions
These belong to the **`torch` module** and are used to **create new tensors**.

They must be called with the module name:

```python
torch.zeros(...)
torch.ones(...)
torch.arange(...)
torch.tensor(...)
```

These are called **factory functions** because they create new tensor objects.

Example:

```python
import torch

x = torch.zeros(3, 4)
```

Here, `zeros()` is a function inside the `torch` library, so Python needs the prefix `torch.` to know where to find it.

---

### 2. Tensor Methods
These belong to an **existing tensor object**.

They are called directly on the tensor using dot notation.

Examples:

```python
x.reshape(...)
x.numel()
```

These functions operate on an existing tensor rather than creating a new one.

Example:

```python
x = torch.arange(6)

x.numel()
x.reshape(2, 3)
```

Think of it like this:

- `torch.zeros()` → "Create me a tensor."
- `x.reshape()` → "Modify or view this tensor."

---

# Quick Reference: Common PyTorch Functions, Methods, and Attributes

| Name | Type | Called As | Returns | Typical Use |
|------|------|-----------|----------|-------------|
| `torch.arange()` | Module function | `torch.arange()` | Sequence tensor | Generate ranges of values |
| `torch.tensor()` | Module function | `torch.tensor()` | Tensor | Convert Python data to a tensor |
| `torch.zeros()` | Module function | `torch.zeros()` | Tensor of zeros | Initialize tensors |
| `torch.ones()` | Module function | `torch.ones()` | Tensor of ones | Initialize tensors |
| `numel()` | Tensor method | `x.numel()` | Integer | Count elements |
| `reshape()` | Tensor method | `x.reshape()` | Reshaped tensor | Change tensor dimensions |
| `shape` | Tensor attribute | `x.shape` | `torch.Size` object | Inspect tensor dimensions |

*   Tensor: the general term for an array with any number of dimensions.


In [2]:
import torch

*   `PyTorch` provides a variety of functions for creating new tensors prepopulated with values.
*   For example, by invoking `arange(n)`, we can create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included).
*   By default, the interval size is 1.
*   Unless otherwise specified, new tensors are stored in main memory and designated for CPU-based computation.

In [3]:
x = torch.arange(12, dtype=torch.float32) #float32 renders the values with 1 decimal places (e.g. 0. instead of 0)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

*   Each of these values is called an element of the tensor.
*   The tensor x contains 12 elements.
*   We can inspect the total number of elements in a tensor via its numel method.

In [4]:
x.numel() #returns the total number of elements in a tensor, regardless of its shap

12

*   We can access a tensor’s shape (the length along each axis) by inspecting its shape attribute.
*   Because we are dealing with a vector here, the shape contains just a single element and is identical to the size.



In [5]:
x.shape #gives you the dimensions of a tensor

torch.Size([12])

*   We can change the shape of a tensor without altering its size or values, by invoking reshape.
*   For example, we can transform our vector `x` whose shape is `(12,)` to a matrix X with shape `(3, 4)`.
*   This new shape (up dimension) must be performed via multiplication.
*   This new tensor retains all elements but reconfigures them into a matrix.
*   Notice that the elements of our vector are laid out one row at a time and thus `x[3] == X[0, 3]`.



In [6]:
x = x.reshape(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

*   A simple hack is to place a `-1` to the `reshape()` function, which work out one component of the shape given the rest.



In [7]:
x = x.reshape(-1,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
x = x.reshape(3,-1)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

*   Practitioners often need to work with tensors initialized to contain all 0s or 1s.
*   We can construct a tensor with all elements set to 0 and a shape of `(2, 3, 4)` via the zeros function.

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

*   Similarly, we can create a tensor with all 1s by invoking ones.


In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

*   We often wish to sample each element randomly (and independently) from a given probability distribution.
*   For example, the parameters of neural networks are often initialized randomly.
*  The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.

In [15]:
torch.randn(3, 4) #creates a mean of 0 and standard deviation of 1 by default

tensor([[ 2.2387, -0.1671,  2.4567, -0.7807],
        [-1.4649,  1.1631,  0.7676, -0.0806],
        [ 0.0243,  1.6942, -1.0884, -0.3697]])

*   Finally, we can construct tensors by supplying the exact values for each element by supplying (possibly nested) Python list(s) containing numerical literals.
*   Here, we construct a matrix with a list of lists, where the outermost list corresponds to axis 0, and the inner list corresponds to axis 1.

In [17]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# 2.1.2. Indexing and Slicing

In [22]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

*   As with Python lists, we can access tensor elements by indexing (starting with 0).
*   To access an element based on its position relative to the end of the list, we can use negative indexing.
*   Finally, we can access whole ranges of indices via slicing (e.g., `X[start:stop]`), where the returned value includes the first index (`start`) but not the last (`stop`).
*   Finally, when only one index (or slice) is specified for a particular-order tensor, it is applied along axis 0.
*   Thus, in the following code, `[-1]` selects the last row and `[1:3]` selects the second and third rows.  


   

In [21]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

*   Beyond reading them, we can also write elements of a matrix by specifying indices.

In [24]:
x[1,2] = 17 # row 1, column 2 is now 17
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

*   If we want to assign multiple elements the same value, we apply the indexing on the left-hand side of the assignment operation.
*   For instance, `[:2, :]` accesses the first and second rows, where `:` takes all the elements along axis 1 (column).
*   While we discussed indexing for matrices, this also works for vectors and for tensors of more than two dimensions.





In [25]:
x[:2, :] = 12 # all columns of rows 0 and 1 are now 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# 2.1.3. Operations

## Quick Reference: Common PyTorch Tensor Operations

| Operation | Type | Called As | Returns | Typical Use |
|----------|------|-----------|----------|-------------|
| `torch.exp()` | Unary operation | `torch.exp(x)` | Tensor | Compute the exponential ($e^x$) element-wise |
| `torch.log()` | Unary operation | `torch.log(x)` | Tensor | Compute the natural logarithm element-wise |
| `torch.sqrt()` | Unary operation | `torch.sqrt(x)` | Tensor | Compute the square root element-wise |
| `torch.abs()` | Unary operation | `torch.abs(x)` | Tensor | Compute absolute values |
| `torch.sin()` | Unary operation | `torch.sin(x)` | Tensor | Compute sine element-wise |
| `torch.cos()` | Unary operation | `torch.cos(x)` | Tensor | Compute cosine element-wise |
| `torch.sum()` | Reduction operation | `torch.sum(x)` | Scalar or tensor | Sum tensor elements |
| `torch.mean()` | Reduction operation | `torch.mean(x)` | Scalar or tensor | Compute the average |
| `torch.max()` | Reduction operation | `torch.max(x)` | Scalar or tensor | Find the maximum value |
| `torch.min()` | Reduction operation | `torch.min(x)` | Scalar or tensor | Find the minimum value |
| `torch.argmax()` | Reduction operation | `torch.argmax(x)` | Integer tensor | Find the index of the maximum value |
| `torch.argmin()` | Reduction operation | `torch.argmin(x)` | Integer tensor | Find the index of the minimum value |
| `torch.cat()` | Combination operation | `torch.cat((x, y), dim=0)` | Tensor | Concatenate tensors along an existing dimension |
| `torch.stack()` | Combination operation | `torch.stack((x, y), dim=0)` | Tensor | Stack tensors along a new dimension |
| `torch.matmul()` | Linear algebra operation | `torch.matmul(x, y)` | Tensor | Matrix multiplication |
| `torch.transpose()` | Linear algebra operation | `torch.transpose(x, 0, 1)` | Tensor | Swap two tensor dimensions |
| `reshape()` | Shape operation | `x.reshape(...)` | Tensor | Change tensor shape |
| `flatten()` | Shape operation | `x.flatten()` | Tensor | Flatten a tensor into one dimension |
| `squeeze()` | Shape operation | `x.squeeze()` | Tensor | Remove dimensions of size 1 |
| `unsqueeze()` | Shape operation | `x.unsqueeze(dim)` | Tensor | Add a dimension of size 1 |
| `permute()` | Shape operation | `x.permute(...)` | Tensor | Rearrange tensor dimensions |
| `clone()` | Utility operation | `x.clone()` | Tensor | Create a copy of a tensor |
| `detach()` | Utility operation | `x.detach()` | Tensor | Remove tensor from the computation graph |

*   Now that we know how to construct tensors and how to read from and write to their elements, we can begin to manipulate them with various mathematical operations.
*   Among the most useful of these are the elementwise operations. These apply a standard scalar operation to each element of a tensor.
*   For functions that take two tensors as inputs, elementwise operations apply some standard binary operator on each pair of corresponding elements.
*   We can create an elementwise function from any function that maps from a scalar to a scalar.

*   In mathematical notation, we denote such unary scalar operators (taking one input) by the signature$
f:\mathbb{R}\rightarrow\mathbb{R}
$.
*   This just means that the function maps from any real number onto some other real number.
*   Most standard operators, including unary ones like $e^x$, can be applied elementwise.





In [26]:
torch.exp(x) #computes the exponential of every element in the tensor x

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

*   Likewise, we denote binary scalar operators, which map pairs of real numbers to a (single) real number via the signature $f: \mathbb{R}, \mathbb{R} \rightarrow \mathbb{R}$.
*   Given any two vectors $\mathbf{u}$ and $\mathbf{v}$ of the same shape, and a binary operator $\mathbf{f}$, we can produce a vector $\mathbf{c} = F(\mathbf{u},\mathbf{v})$ by setting $c_i \gets f(u_i, v_i)$ for all $i$, where $c_i, u_i$, and $v_i$ are the $i^\textrm{th}$ elements of vectors $c$, $u$, and $v$.
*   Here, we produced the vector-valued $F: \mathbb{R}^d, \mathbb{R}^d \rightarrow \mathbb{R}^d$ by lifting the scalar function to an elementwise vector operation.
*   The common standard arithmetic operators for addition (+), subtraction (-), multiplication (*), division (/), and exponentiation (**) have all been lifted to elementwise operations for identically-shaped tensors of arbitrary shape.
*   In addition to elementwise computations, we can also perform linear algebraic operations, such as dot products and matrix multiplications. We will elaborate on these in Section 2.3.


In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x-y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

*   We can also concatenate multiple tensors, stacking them end-to-end to form a larger one. We just need to provide a list of tensors and tell the system along which axis to concatenate.
*   The example below shows what happens when we concatenate two matrices along rows (axis 0) instead of columns (axis 1).
*   We can see that the first output’s axis-0 length ($6$) is the sum of the two input tensors’ axis-0 lengths ($3 + 3$); while the second output’s axis-1 length ($8$) is the sum of the two input tensors’ axis-1 lengths ($4 + 4$).

   

In [28]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1) # at dim=0, Y is conactenated by following X. at dim=1, the axis of Y and X are glued together

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

*   Sometimes, we want to construct a binary tensor via logical statements.
*   Take X == Y as an example. For each position i, j, if X[i, j] and Y[i, j] are equal, then the corresponding entry in the result takes value 1, otherwise it takes value 0.

In [29]:
X == Y #compares each axis between X and Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

*   Summing all the elements in the tensor yields a tensor with only one element.




In [30]:
X.sum() # all elements of X or arange(12) are added together from 0 to 11, which equals 66

tensor(66.)

# 2.1.4. Broadcasting

*   By now, you know how to perform elementwise binary operations on two tensors of the same shape.
*   Under certain conditions, even when shapes differ, we can still perform elementwise binary operations by invoking the broadcasting mechanism.
*   Broadcasting works according to the following two-step procedure:
> *   (i) expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape;
> *   (ii) perform an elementwise operation on the resulting arrays.

In [32]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

*   Since $a$ and $b$ are $3\times1$ and $1\times2$ matrices, respectively, their shapes do not match up.
*   Broadcasting produces a larger $3\times2$ matrix by replicating matrix $a$ along the columns and matrix $b$ along the rows before adding them elementwise.

In [33]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 2.1.5. Saving Memory

*   Running operations can cause new memory to be allocated to host results.
*   If we write $Y = X + Y$, we dereference the tensor that $Y$ used to point to and instead point $Y$ at the newly allocated memory.
*   We can demonstrate this issue with Python’s `id()` function, which gives us the exact address of the referenced object in memory.
*   Note that after we run $Y = Y + X$, `id(Y)` points to a different location.
*   That is because Python first evaluates $Y + X$, allocating new memory for the result and then points $Y$ to this new location in memory.

In [34]:
before = id(Y)
Y = Y + X
id(Y) == before

False

*   This might be undesirable for two reasons.
> *   First, we do not want to run around allocating memory unnecessarily all the time.
>> *  In machine learning, we often have hundreds of megabytes of parameters and update all of them multiple times per second.
>> *  Whenever possible, we want to perform these updates in place.
> *   Second, we might point at the same parameters from multiple variables.
>> *  If we do not update in place, we must be careful to update all of these references, lest we spring a memory leak or inadvertently refer to stale parameters.

*   Fortunately, performing in-place operations is easy.
> *   We can assign the result of an operation to a previously allocated array $Y$ by using slice notation: `Y[:] = <expression>`.
> *   To illustrate this concept, we overwrite the values of tensor $Z$, after initializing it, using `zeros_like`, to have the same shape as $Y$.

In [37]:
Z = torch.zeros_like(Y)    #creates a tensor full of zeros in the shape of Y, zeros_like copies the shape of another tensor whereas you need to specify it with zeros()
print('id(Z):', id(Z))
Z[:] = X + Y               #all elements of Z equals to X + Y
print('id(Z):', id(Z))     #in-place operation has been performed

id(Z): 136538633204384
id(Z): 136538633204384


*   If the value of $X$ is not reused in subsequent computations, we can also use `X[:] = X + Y` or `X += Y` to reduce the memory overhead of the operation.


In [38]:
before = id(X)
X += Y
id(X) == before

True

# 2.1.6. Conversion to Other Python Objects

*   Converting to a NumPy tensor (`ndarray`), or vice versa, is easy.
*   The torch tensor and NumPy array will share their underlying memory, and changing one through an in-place operation will also change the other.





In [39]:
A = X.numpy() #tensor converted to NumPy
B = torch.from_numpy(A) #NumPy converted to tensor
type(A), type(B)

(numpy.ndarray, torch.Tensor)

*   To convert a size-1 tensor to a Python scalar, we can invoke the `item()` function or Python’s built-in functions.
*   Note that `torch.item()` is different than the Python native `dict.items()` function used to return key-value pairs.

In [40]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 2.1.7. Summary

*   The tensor class is the main interface for storing and manipulating data in deep learning libraries.
*   Tensors provide a variety of functionalities including:
> *   construction routines;
> *   indexing and slicing;
> *   basic mathematics operations;
> *   broadcasting;
> *   memory-efficient assignment;
> *   and conversion to and from other Python objects.
     

# 2.1.8. Exercises

1. Run the code in this section. Change the conditional statement `X == Y` to `X < Y` or `X > Y`, and then see what kind of tensor you can get.
2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?